* This is my personal spacemacs config but I am interested in optimizing the config to share more widely.
* One of the issues with adopting spacemacs is the massive api and infintely configurable nature. I want to produce a formula that works for common web developement scenarios. 
* What does that mean?
** javascript html css (for sure)
** typescipt, flow (definitely)
** reasonml (would like to have)
* I would also like to have a little more solid theming.
** Start with just a few themes that apply to everything.
*** display :: theme - filepath - major mode - git snapshot - error reporting
*** must look consistent across all windows -> possible exception with shell 
**** file tree icons and highlighting need to be improved
**** flycheck window highlighting current line error needs to be controlled for best legibility
**** shell needs to have same background color as text editor
** git diff needs to look sweet like vs code
*** should have easy controls that are clearly described 
**** next and previous
**** select old/new branch or commit should have buttons with (key stroke) labels
**** should be way to revert
*** label branches/commits clearly

* Another difficulty of spacemacs is the upgrade process. You have to manually go through a diff file when you pull from the spacemacs repo. Is that a big deal? If you update frequently it can be a challenge to try and interpret your intential changes to the config file versus default settings. While I could be more active with this process I think it is a significant barrier to entry when compared with vs code.
** the challenge is incorporating user defined configs with an evolving code base
*** It would be nice if you could define your stuff in a seperate file form the default setup in init.e.
*** What should happen to settings that you have configed but get dropped from the core init.el on an upgrade?
**** proposal - anything that was not user set, i.e. the setting is in the default state will just get removed on updgrade.
**** proposal - anything that was set will be added to user-config, but commented out at the very top of that function body

* Getting setup
** make a git repo for your init.el or entire .spacemacs.d directory
** add a .gitignore file with `.env` as the first line
** spacemacs creates a `.env` file that is aggregated from various config files on your local machine that may potentially have secrets.
** everytime you make a change to your init.el file or any imported code make a git commit with a clear message


* Debugging Spacemacs

* Quick Tips
** Do you ever find you have pressed some keys that did something unexpected?
*** C-h l
** Do you want to code fold html tags? 
*** SPC m z
*** folds and unfolds!

